import type { School, Solution, Workflow } from './types'

export const mockSchools: School[] = [
  {
    id: '1',
    name: '聖保羅男女中學',
    district: '中西區',
    type: '直資',
    level: '中學',
    website: 'https://www.spcc.edu.hk',
    maturityGrade: 'A',
    overallScore: 92,
    dimensions: {
      curriculum: 95,
      infrastructure: 90,
      teacherTraining: 88,
      studentLiteracy: 94,
      governance: 92,
      ethics: 90,
      partnership: 95,
      innovation: 92,
    },
    lastUpdated: '2024-03-15',
    status: 'completed',
  },
  {
    id: '2',
    name: '拔萃男書院',
    district: '九龍城區',
    type: '直資',
    level: '中學',
    website: 'https://www.dbs.edu.hk',
    maturityGrade: 'A',
    overallScore: 89,
    dimensions: {
      curriculum: 88,
      infrastructure: 92,
      teacherTraining: 85,
      studentLiteracy: 90,
      governance: 88,
      ethics: 92,
      partnership: 90,
      innovation: 88,
    },
    lastUpdated: '2024-03-14',
    status: 'completed',
  },
  {
    id: '3',
    name: '英華書院',
    district: '深水埗區',
    type: '直資',
    level: '中學',
    website: 'https://www.yingwa.edu.hk',
    maturityGrade: 'B',
    overallScore: 78,
    dimensions: {
      curriculum: 80,
      infrastructure: 75,
      teacherTraining: 82,
      studentLiteracy: 78,
      governance: 76,
      ethics: 80,
      partnership: 75,
      innovation: 78,
    },
    lastUpdated: '2024-03-13',
    status: 'completed',
  },
  {
    id: '4',
    name: '喇沙書院',
    district: '九龍城區',
    type: '資助',
    level: '中學',
    website: 'https://www.lasalle.edu.hk',
    maturityGrade: 'B',
    overallScore: 75,
    dimensions: {
      curriculum: 72,
      infrastructure: 78,
      teacherTraining: 75,
      studentLiteracy: 76,
      governance: 74,
      ethics: 78,
      partnership: 72,
      innovation: 75,
    },
    lastUpdated: '2024-03-12',
    status: 'completed',
  },
  {
    id: '5',
    name: '華仁書院（九龍）',
    district: '油尖旺區',
    type: '資助',
    level: '中學',
    website: 'https://www.wyk.edu.hk',
    maturityGrade: 'C',
    overallScore: 62,
    dimensions: {
      curriculum: 60,
      infrastructure: 65,
      teacherTraining: 58,
      studentLiteracy: 62,
      governance: 64,
      ethics: 68,
      partnership: 58,
      innovation: 60,
    },
    lastUpdated: '2024-03-11',
    status: 'completed',
  },
  {
    id: '6',
    name: '培正中學',
    district: '九龍城區',
    type: '資助',
    level: '中學',
    website: 'https://www.puiching.edu.hk',
    maturityGrade: 'C',
    overallScore: 58,
    dimensions: {
      curriculum: 55,
      infrastructure: 62,
      teacherTraining: 52,
      studentLiteracy: 58,
      governance: 60,
      ethics: 65,
      partnership: 52,
      innovation: 58,
    },
    lastUpdated: '2024-03-10',
    status: 'analyzing',
  },
  {
    id: '7',
    name: '聖士提反書院',
    district: '南區',
    type: '直資',
    level: '中學',
    website: 'https://www.ssc.edu.hk',
    maturityGrade: 'B',
    overallScore: 72,
    dimensions: {
      curriculum: 70,
      infrastructure: 75,
      teacherTraining: 68,
      studentLiteracy: 74,
      governance: 72,
      ethics: 76,
      partnership: 70,
      innovation: 72,
    },
    lastUpdated: '2024-03-09',
    status: 'completed',
  },
  {
    id: '8',
    name: '新界鄉議局元朗區中學',
    district: '元朗區',
    type: '官立',
    level: '中學',
    website: 'https://www.nthykyldss.edu.hk',
    maturityGrade: 'D',
    overallScore: 42,
    dimensions: {
      curriculum: 40,
      infrastructure: 45,
      teacherTraining: 38,
      studentLiteracy: 42,
      governance: 44,
      ethics: 48,
      partnership: 38,
      innovation: 40,
    },
    lastUpdated: '2024-03-08',
    status: 'pending',
  },
]

export const mockSolutions: Solution[] = [
  {
    id: 's1',
    name: 'AI 課程整合套件',
    category: '課程發展',
    description: '完整的 K-12 AI 課程體系，包含教材、教案及評估工具',
    targetDimensions: ['curriculum', 'studentLiteracy'],
    minGrade: 'C',
    provider: 'EdTech Solutions HK',
    features: ['模組化課程', '跨學科整合', '在線評估', '學習分析'],
  },
  {
    id: 's2',
    name: '教師 AI 專業發展計劃',
    category: '師資培訓',
    description: '分層次的教師 AI 能力培訓，從基礎到高階應用',
    targetDimensions: ['teacherTraining', 'curriculum'],
    minGrade: 'D',
    provider: '香港教育大學',
    features: ['認證課程', '工作坊', '同儕學習', '持續支援'],
  },
  {
    id: 's3',
    name: '智慧校園基礎設施方案',
    category: '基礎建設',
    description: '一站式 AI 基礎設施升級，包含硬件、軟件及網絡優化',
    targetDimensions: ['infrastructure', 'governance'],
    minGrade: 'D',
    provider: 'Smart Campus Tech',
    features: ['雲端平台', 'AI 工作站', '高速網絡', '安全管理'],
  },
  {
    id: 's4',
    name: 'AI 倫理與安全框架',
    category: '管理策略',
    description: '學校 AI 使用的倫理指引、政策模板及安全協議',
    targetDimensions: ['ethics', 'governance'],
    minGrade: 'C',
    provider: 'AI Ethics Institute',
    features: ['政策模板', '培訓教材', '審核工具', '合規檢查'],
  },
  {
    id: 's5',
    name: '產學合作平台',
    category: '合作夥伴',
    description: '連接學校與業界的 AI 項目合作平台',
    targetDimensions: ['partnership', 'innovation'],
    minGrade: 'B',
    provider: 'InnoHub HK',
    features: ['項目配對', '業界導師', '實習機會', '資源共享'],
  },
  {
    id: 's6',
    name: '學生 AI 創新實驗室',
    category: '創新實踐',
    description: '為學生提供 AI 項目開發的完整環境和指導',
    targetDimensions: ['innovation', 'studentLiteracy'],
    minGrade: 'B',
    provider: 'Future Ready Labs',
    features: ['項目孵化', '技術支援', '比賽指導', '成果展示'],
  },
]

export const mockWorkflows: Workflow[] = [
  {
    id: 'w1',
    schoolId: '6',
    schoolName: '培正中學',
    stage: 'analysis',
    status: 'active',
    createdAt: '2024-03-01',
    updatedAt: '2024-03-10',
    assignee: '陳老師',
    notes: ['已完成初步評估', '待進行深度訪談'],
  },
  {
    id: 'w2',
    schoolId: '8',
    schoolName: '新界鄉議局元朗區中學',
    stage: 'discovery',
    status: 'active',
    createdAt: '2024-03-05',
    updatedAt: '2024-03-08',
    assignee: '李顧問',
    notes: ['已獲取學校官網數據', '等待學校確認參與'],
  },
  {
    id: 'w3',
    schoolId: '5',
    schoolName: '華仁書院（九龍）',
    stage: 'recommendation',
    status: 'active',
    createdAt: '2024-02-15',
    updatedAt: '2024-03-11',
    assignee: '王經理',
    notes: ['分析完成', '已生成方案建議', '待學校審閱'],
  },
  {
    id: 'w4',
    schoolId: '3',
    schoolName: '英華書院',
    stage: 'implementation',
    status: 'active',
    createdAt: '2024-01-20',
    updatedAt: '2024-03-13',
    assignee: '張顧問',
    notes: ['方案已批准', '師資培訓進行中', '基礎設施升級計劃中'],
  },
  {
    id: 'w5',
    schoolId: '1',
    schoolName: '聖保羅男女中學',
    stage: 'review',
    status: 'completed',
    createdAt: '2023-09-01',
    updatedAt: '2024-02-28',
    assignee: '陳老師',
    notes: ['所有項目已完成', '成效評估優異', '已建立持續合作關係'],
  },
]

export const districtStats = [
  { district: '中西區', schools: 45, avgScore: 72 },
  { district: '灣仔區', schools: 38, avgScore: 68 },
  { district: '東區', schools: 52, avgScore: 65 },
  { district: '南區', schools: 28, avgScore: 70 },
  { district: '油尖旺區', schools: 42, avgScore: 62 },
  { district: '深水埗區', schools: 48, avgScore: 58 },
  { district: '九龍城區', schools: 55, avgScore: 74 },
  { district: '黃大仙區', schools: 35, avgScore: 55 },
  { district: '觀塘區', schools: 58, avgScore: 52 },
  { district: '沙田區', schools: 62, avgScore: 64 },
  { district: '大埔區', schools: 32, avgScore: 60 },
  { district: '北區', schools: 28, avgScore: 48 },
  { district: '元朗區', schools: 45, avgScore: 45 },
  { district: '屯門區', schools: 52, avgScore: 50 },
  { district: '荃灣區', schools: 35, avgScore: 58 },
  { district: '葵青區', schools: 48, avgScore: 54 },
  { district: '西貢區', schools: 38, avgScore: 62 },
  { district: '離島區', schools: 18, avgScore: 42 },
]

export const gradeDistribution = [
  { grade: 'A', count: 45, percentage: 8 },
  { grade: 'B', count: 125, percentage: 22 },
  { grade: 'C', count: 245, percentage: 43 },
  { grade: 'D', count: 155, percentage: 27 },
]
